// <auto-generated />
using System;
using CestlheureduBK.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CestlheureduBK.Migrations
{
    [DbContext(typeof(BKDbContext))]
    partial class BKDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("CestlheureduBK.Model.MenuDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("PriceL")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("PriceXL")
                        .HasColumnType("decimal(4, 2)");

                    b.HasKey("Id");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("CestlheureduBK.Model.OfferDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromotionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("CestlheureduBK.Model.ProductDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(4, 2)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CestlheureduBK.Model.PromotionDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("MenuDbPromotionDb", b =>
                {
                    b.Property<string>("MenusId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromotionsId")
                        .HasColumnType("TEXT");

                    b.HasKey("MenusId", "PromotionsId");

                    b.HasIndex("PromotionsId");

                    b.ToTable("MenuDbPromotionDb");
                });

            modelBuilder.Entity("ProductDbPromotionDb", b =>
                {
                    b.Property<string>("ProductsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromotionsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductsId", "PromotionsId");

                    b.HasIndex("PromotionsId");

                    b.ToTable("ProductDbPromotionDb");
                });

            modelBuilder.Entity("CestlheureduBK.Model.OfferDb", b =>
                {
                    b.HasOne("CestlheureduBK.Model.PromotionDb", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("MenuDbPromotionDb", b =>
                {
                    b.HasOne("CestlheureduBK.Model.MenuDb", null)
                        .WithMany()
                        .HasForeignKey("MenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CestlheureduBK.Model.PromotionDb", null)
                        .WithMany()
                        .HasForeignKey("PromotionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductDbPromotionDb", b =>
                {
                    b.HasOne("CestlheureduBK.Model.ProductDb", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CestlheureduBK.Model.PromotionDb", null)
                        .WithMany()
                        .HasForeignKey("PromotionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
